name: Build

on:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"
    branches: [ master ]

jobs:
  build:
    name: Lint, test and build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Check with ESLint
      run: yarn lint
    - name: Run unit tests
      run: yarn test --watchAll=false
    - name: Build
      run: yarn build
    - name: Tar files
      run: tar -cvzf build.tar.gz ./build
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build.tar.gz

  deploy:
    name: Deploy to AWS S3
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
      - name: Extract artifact
        run: tar -xf build.tar.gz
      - name: Upload files to the bucket
        run: |
          aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET_NAME }}
      - name: Clear Cloudfront cache
        run: |
          aws cloudfront create-invalidation --distribution-id {{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
