name: Build

on:
    push:
        paths:
            - "src/**"
            - "public/**"
            - ".github/workflows/**"
            - ".env"
            - "package.json"
            - "yarn.lock"
        branches: [master]

jobs:
    build:
        name: Test, build and deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js 19
              uses: actions/setup-node@v2
              with:
                  node-version: "19.x"

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Check with ESLint
              run: yarn lint

            - name: Run unit tests
              run: yarn test --watchAll=false

            - name: Build
              run: yarn build

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Upload files to the bucket
              run: |
                  aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete

            - name: Clear Cloudfront cache
              run: |
                  aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
