# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing

on:
  pull_request:
    paths:
      - "src/**"
      - "public/**"
      - ".github/workflows/**"
      - ".env"
      - "package.json"
      - "yarn.lock"
jobs:
  build:
    name: Lint, test and build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: "16" # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        cache: "yarn"
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Check with ESLint
      run: yarn lint
    - name: Run unit tests
      run: yarn test --watchAll=false
    - name: Build
      run: yarn build
